name: google_maps_flutter_example
description: Demonstrates how to use the google_maps_flutter plugin.

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  google_maps_flutter:
    path: ../
  flutter_plugin_android_lifecycle: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    path: ../../../integration_test
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/